apiVersion: volterra.upbound.io/v1alpha1
kind: CloudCredentials
metadata:
  name: hello-crossplane-test
spec:
  forProvider:
    name: hello-crossplane-creds
    description: "GCP Credentials"
    namespace: "system"
    gcpCredFile:
      - credentialFile:
        - clearSecretInfo:
            - url: "string:///some_secret_value_base_64d"
  providerConfigRef:
    name: default
