apiVersion: volterra.upbound.io/v1alpha1
kind: HTTPLoadbalancer
metadata:
  name: hello-crossplane-lb
spec:
  forProvider:
    name: hello-crossplane-lb
    namespaceRef:
      name: hello-crossplane-test
    description: HTTPS loadbalancer object for external service
    domains:
      - "crossplane.demo.f5octo.dev"
    advertiseOnPublicDefaultVip: false
    defaultRoutePools:
      - pool:
          - name: hello-crossplane
            namespace: hello-crossplane-test
    httpsAutoCert:
      - addHsts: true
        httpRedirect: true
        noMtls: true
    appFirewall:
      - name: hello-crossplane-waf
        namespace: hello-crossplane-test
    disableRateLimit: true
    roundRobin: true
    servicePoliciesFromNamespace: true
    noChallenge: true
  providerConfigRef:
    name: default


# // resource "volterra_http_loadbalancer" "this" {
# // 	name                            = "${var.name_prefix}-loadbalancer"
# // 	namespace                       = var.namespace
# // 	description                     = "HTTPS loadbalancer object for external service"
# // 	domains                         = [var.app_fqdn]
# // 	advertise_on_public_default_vip = true
# // 	default_route_pools {
# // 	  pool {
# // 		name      = volterra_origin_pool.this.name
# // 		namespace = var.namespace
# // 	  }
# // 	}
# // 	https_auto_cert {
# // 	  add_hsts      = true
# // 	  http_redirect = true
# // 	  no_mtls       = true
# // 	}
# // 	app_firewall {
# // 	  name      = "${var.name_prefix}-app-firewall"
# // 	  namespace = var.namespace
# // 	}
# // 	disable_rate_limit              = true
# // 	round_robin                     = true
# // 	service_policies_from_namespace = true
# // 	no_challenge                    = true
# //   }
